[package]
name = "libvim_rs"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[lib]
name="libvim_rs"
path="lib.rs"

[dependencies]
libc = "0.2.112"

[build-dependencies]
bindgen = "0.69.1"
cc = "1.0.72"
pkg-config = "0.3.24"

